// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// local_ids
IntegerVector local_ids(SEXP context);
RcppExport SEXP _rsyntax_local_ids(SEXP contextSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type context(contextSEXP);
    rcpp_result_gen = Rcpp::wrap(local_ids(context));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rsyntax_local_ids", (DL_FUNC) &_rsyntax_local_ids, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rsyntax(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
