# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

local_ids <- function(context) {
    .Call('_rsyntax_local_ids', PACKAGE = 'rsyntax', context)
}

